# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40b457abd7fe4c166f0c7280c7bdc88b22efecd1a818e333417b9c6a2da16a8af1800dff66683ec318df275e95de218ea5be09ceb32b28bd3e5350b831b0212

test:
  secret_key_base: 38daaefd11a4cb98017e37e62f07d30cc538ab763448f92ad752630ef851c0c5646c1d3bc7c95ce71995ab04653c282d3744af277612fac5317ea30ffad0441c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
